# Generated by Django 5.1.1 on 2024-10-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Dai', max_length=150),
            preserve_default=False,
        ),
    ]
