# Generated by Django 5.1.1 on 2024-11-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_song_playlist_playlistsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='acousticness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artist_genres',
            field=models.JSONField(default='pop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artist_names',
            field=models.CharField(default='bts', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artist_pop',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='danceability',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='duration_ms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='instrumentalness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='liveness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='loudness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Minor'), (1, 'Major')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='num_followers',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='speechiness',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='tempo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='time_signature',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='track_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='track_pop',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='uri',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='uri_artist',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='valence',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
