# Generated by Django 5.1.1 on 2024-12-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_remove_song_album_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_img_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
