# Generated by Django 5.1.1 on 2024-12-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_song_artist_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=100)),
                ('genres', models.JSONField()),
                ('num_of_followers', models.IntegerField()),
                ('popularity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_img_url',
            new_name='song_img_url',
        ),
    ]
