# Generated by Django 5.1.1 on 2025-02-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_favoritesong'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tag',
            field=models.CharField(choices=[('Artist', 'Artist'), ('Playlist', 'Playlist'), ('Audiobook', 'Audiobook'), ('Podcast', 'Podcast')], default='Playlist', max_length=50),
        ),
    ]
